### ISSUE TITLE
Coordinates for different maven repositories doesn't seem to get picked up

### ISSUE THREAD

**Issue by aisamu** [jpmonettas/clograms#9] opened 2019-12-06 15:31 UTC
Hi!

We have a CLJ/CLJS project with mixed public/private artefacts and we can't get the tool to correctly resolve dependencies on our private repository.

The coordinate points to a "regular" AWS S3 private maven repo:
 
```clojure
 :mvn/repos {"our-maven" {:url "s3p://repo-url/releases/" :no-auth true}}
``` 

We've tried adding the maven coordinates to the project's `deps.edn`, the system/user's `deps.edn` and also inlining them with the shell command.

Here's the output of the example command:
```shell
$ clj -Sdeps '{:deps {clograms {:mvn/version "0.1.7"}}}' -m clograms.server . cljs
```

```clojure
{:clojure.main/message "Execution error (ExceptionInfo) at
 clojure.tools.deps.alpha.extensions.maven/get-artifact (maven.clj:118).\nCould
 not find artifact com.company:shared-artifact:jar:0.1.0 in central
 (https://repo1.maven.org/maven2/)\n",
 :clojure.main/triage
 {:clojure.error/class clojure.lang.ExceptionInfo,
  :clojure.error/line 118,
  :clojure.error/cause "Could not find artifact
  com.company:shared-artifact:jar:0.1.0 in central
  (https://repo1.maven.org/maven2/)",
  :clojure.error/symbol clojure.tools.deps.alpha.extensions.maven/get-artifact,
  :clojure.error/source "maven.clj",
  :clojure.error/phase :execution},
 :clojure.main/trace
 {:via
  [{:type clojure.lang.ExceptionInfo,
    :message "Could not find artifact com.company:shared-artifact:jar:0.1.0 in
    central (https://repo1.maven.org/maven2/)",
    :data
    {:lib com.company/shared-artifact,
     :coord {:mvn/version "0.1.0", :deps/manifest :mvn}},
    :at
    [clojure.tools.deps.alpha.extensions.maven$get_artifact invokeStatic "maven.clj" 118]}],
  :trace
  [[clojure.tools.deps.alpha.extensions.maven$get_artifact invokeStatic "maven.clj" 118]
   [clojure.tools.deps.alpha.extensions.maven$get_artifact invoke "maven.clj" 107]
   [clojure.tools.deps.alpha.extensions.maven$eval6873$fn__6875 invoke "maven.clj" 126]
   [clojure.lang.MultiFn invoke "MultiFn.java" 244]
   [clojure.tools.deps.alpha$lib_paths$fn__7254 invoke "alpha.clj" 207]
   [clojure.core.protocols$iter_reduce invokeStatic "protocols.clj" 49]
   [clojure.core.protocols$fn__8140 invokeStatic "protocols.clj" 75]
   [clojure.core.protocols$fn__8140 invoke "protocols.clj" 75]
   [clojure.core.protocols$fn__8088$G__8083__8101 invoke "protocols.clj" 13]
   [clojure.core$reduce invokeStatic "core.clj" 6828]
   [clojure.core$reduce invoke "core.clj" 6810]
   [clojure.tools.deps.alpha$lib_paths invokeStatic "alpha.clj" 203]
   [clojure.tools.deps.alpha$lib_paths invoke "alpha.clj" 201]
   [clojure.tools.deps.alpha$resolve_deps invokeStatic "alpha.clj" 233]
   [clojure.tools.deps.alpha$resolve_deps invoke "alpha.clj" 214]
   [clindex.scanner$scan_all_projects invokeStatic "scanner.clj" 116]
   [clindex.scanner$scan_all_projects invoke "scanner.clj" 108]
   [clindex.api$index_project_BANG_ invokeStatic "api.clj" 146]
   [clindex.api$index_project_BANG_ invoke "api.clj" 133]
   [clograms.core$re_index_all invokeStatic "core.clj" 30]
   [clograms.core$re_index_all invoke "core.clj" 27]
   [clograms.server$_main invokeStatic "server.clj" 38]
   [clograms.server$_main doInvoke "server.clj" 28]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.core$apply invokeStatic "core.clj" 665]
   [clojure.main$main_opt invokeStatic "main.clj" 514]
   [clojure.main$main_opt invoke "main.clj" 510]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]],
  :cause
  "Could not find artifact com.company:shared-artifact:jar:0.1.0 in central
  (https://repo1.maven.org/maven2/)",
  :data
  {:lib com.company/shared-artifact,
   :coord {:mvn/version "0.1.0", :deps/manifest :mvn}}}}
```

Please let me know if you'd like us to test something against our current environment.

This looks like an amazing tool!

**Comment by jpmonettas** [comment] 2019-12-07 00:43
Hi, thanks for reporting it @aisamu. 
I haven't use s3 repos but clograms uses tools.deps to retrieve dependencies so it should be supported as long as tools.deps support it (which I think it does).
Maybe upgrading to the latest tools.deps version fix it, I'll try to release a new version during the weekend.

**Comment by jpmonettas** [comment] 2019-12-07 14:05
Maybe related to https://github.com/jpmonettas/clindex/issues/2

Sorry I didn't do a good job explaining this yesterday. Clograms uses [clindex](https://github.com/jpmonettas/clindex) to retrieve deps and index everything, which uses tools.deps.alpha in  this [line](https://github.com/jpmonettas/clindex/blob/master/src/clindex/scanner.clj#L116) and that is all about resolving deps.

It should be merging whatever repos are defined in deps.edn with `clojure.tools.deps.alpha.util.maven/standard-repos`. I'm currently not using any other repo than clojars or central maven in my projects but I'll try and see if I can reproduce.

**Comment by jpmonettas** [comment] 2019-12-07 15:04
I wasn't able to reproduce the problem, I tested with [this test project](https://github.com/jpmonettas/clindex/blob/master/test-resources/test-project/deps.edn) that contains a dep with a coordinate to a non standard s3 repo and it worked fine.

Anyway I upgraded tools.deps so latest clograms version (0.1.9) should be pulling the latest one.

Please let me know if this is still a issue.

**Comment by aisamu** [comment] 2019-12-07 15:50
Just tested 0.1.9, but still doesn't work :(

The output is actually more interesting when I delete the artefacts before running it:
```shell
$ clj -Sdeps '{:deps {clograms {:mvn/version "0.1.9"}}}' -m clograms.server . cljs

Downloading: refactor-nrepl/refactor-nrepl/2.5.0-SNAPSHOT/maven-metadata.xml from s3p://s3-maven-url/releases/
[...]
Downloading: com/company/artefact/0.1.0/artefact-0.1.0.pom from s3p://s3-maven-url/releases/
[...]
Indexing  . for platform cljs
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Execution error (ExceptionInfo) at clojure.tools.deps.alpha.extensions.maven/get-artifact (maven.clj:118).
Could not find artifact com.company:artefact:jar:0.1.0 in central (https://repo1.maven.org/maven2/)

Full report at:
/var/folders/s7/ngynyrg15v5f_588d_kqhy8w0000gn/T/clojure-1446140852733353968.edn

$ cat /var/folders/s7/ngynyrg15v5f_588d_kqhy8w0000gn/T/clojure-1446140852733353968.edn
```
```clojure
{:clojure.main/message
 "Execution error (ExceptionInfo) at clojure.tools.deps.alpha.extensions.maven/get-artifact (maven.clj:118).\nCould not find artifact com.company:artefact:jar:0.1.0 in central (https://repo1.maven.org/maven2/)\n",
 :clojure.main/triage
 {:clojure.error/class clojure.lang.ExceptionInfo,
  :clojure.error/line 118,
  :clojure.error/cause
  "Could not find artifact com.company:artefact:jar:0.1.0 in central (https://repo1.maven.org/maven2/)",
  :clojure.error/symbol
  clojure.tools.deps.alpha.extensions.maven/get-artifact,
  :clojure.error/source "maven.clj",
  :clojure.error/phase :execution},
 :clojure.main/trace
 {:via
  [{:type clojure.lang.ExceptionInfo,
    :message
    "Could not find artifact com.company:artefact:jar:0.1.0 in central (https://repo1.maven.org/maven2/)",
    :data
    {:lib com.company/artefact,
     :coord {:mvn/version "0.1.0", :deps/manifest :mvn}},
    :at
    [clojure.tools.deps.alpha.extensions.maven$get_artifact
     invokeStatic
     "maven.clj"
     118]}],
  :trace
  [[clojure.tools.deps.alpha.extensions.maven$get_artifact
    invokeStatic
    "maven.clj"
    118]
   [clojure.tools.deps.alpha.extensions.maven$get_artifact
    invoke
    "maven.clj"
    107]
   [clojure.tools.deps.alpha.extensions.maven$eval6885$fn__6887
    invoke
    "maven.clj"
    126]
   [clojure.lang.MultiFn invoke "MultiFn.java" 244]
   [clojure.tools.deps.alpha$lib_paths$fn__7279 invoke "alpha.clj" 210]
   [clojure.core.protocols$iter_reduce invokeStatic "protocols.clj" 49]
   [clojure.core.protocols$fn__8140 invokeStatic "protocols.clj" 75]
   [clojure.core.protocols$fn__8140 invoke "protocols.clj" 75]
   [clojure.core.protocols$fn__8088$G__8083__8101
    invoke
    "protocols.clj"
    13]
   [clojure.core$reduce invokeStatic "core.clj" 6828]
   [clojure.core$reduce invoke "core.clj" 6810]
   [clojure.tools.deps.alpha$lib_paths invokeStatic "alpha.clj" 206]
   [clojure.tools.deps.alpha$lib_paths invoke "alpha.clj" 204]
   [clojure.tools.deps.alpha$resolve_deps invokeStatic "alpha.clj" 238]
   [clojure.tools.deps.alpha$resolve_deps invoke "alpha.clj" 217]
   [clojure.tools.deps.alpha$resolve_deps invokeStatic "alpha.clj" 231]
   [clojure.tools.deps.alpha$resolve_deps invoke "alpha.clj" 217]
   [clindex.scanner$scan_all_projects invokeStatic "scanner.clj" 116]
   [clindex.scanner$scan_all_projects invoke "scanner.clj" 108]
   [clindex.api$index_project_BANG_ invokeStatic "api.clj" 156]
   [clindex.api$index_project_BANG_ invoke "api.clj" 143]
   [clograms.core$re_index_all invokeStatic "core.clj" 30]
   [clograms.core$re_index_all invoke "core.clj" 27]
   [clograms.server$_main invokeStatic "server.clj" 38]
   [clograms.server$_main doInvoke "server.clj" 28]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.core$apply invokeStatic "core.clj" 665]
   [clojure.main$main_opt invokeStatic "main.clj" 514]
   [clojure.main$main_opt invoke "main.clj" 510]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]],
  :cause
  "Could not find artifact com.company:artefact:jar:0.1.0 in central (https://repo1.maven.org/maven2/)",
  :data
  {:lib com.company/artefact,
   :coord {:mvn/version "0.1.0", :deps/manifest :mvn}}}}
```

So it gets downloaded by tools-deps, but fails at the indexing phase?

It's indeed strange that it works with the test project. The only difference I can see there is that that's a _public_ s3 bucket, whereas ours is private. Would that make any difference?

**Comment by aisamu** [comment] 2019-12-07 17:34
`clindex` is indeed dropping the configuration from the map before handing it to `tools-deps`, but after fixing that the failure is a bit different (and probably out of my depth):
```diff
modified   src/clindex/scanner.clj
@@ -68,5 +68,5 @@
                           slurp
                           read-string)
-        {:keys [deps paths]} (or
+        {:keys [deps paths :mvn/repos]} (or
                                          ;; tools deps
                                          tool-deps
@@ -84,4 +84,5 @@
     {:project/name main-project-symb
      :deps deps
+     :mvn/repos repos
      :project/dependencies (->> deps keys (into #{}))
      :paths (or paths ["src"])}))
```
Running tests after applying this patch:
```shell
$ clj -A:test:runner

Running tests in #{"test"}

Testing clindex.api-test

Execution error (NullPointerException) at clindex.utils/normalize-path (utils.clj:11).
null

Full report at:
/var/folders/s7/ngynyrg15v5f_588d_kqhy8w0000gn/T/clojure-4923778080242018924.edn

$ cat /var/folders/s7/ngynyrg15v5f_588d_kqhy8w0000gn/T/clojure-4923778080242018924.edn
```
```clojure
{:clojure.main/message
 "Execution error (NullPointerException) at clindex.utils/normalize-path (utils.clj:11).\nnull\n",
 :clojure.main/triage
 {:clojure.error/class java.lang.NullPointerException,
  :clojure.error/line 11,
  :clojure.error/symbol clindex.utils/normalize-path,
  :clojure.error/source "utils.clj",
  :clojure.error/phase :execution},
 :clojure.main/trace
 {:via
  [{:type java.util.concurrent.ExecutionException,
    :message "java.lang.NullPointerException",
    :at [java.util.concurrent.FutureTask report "FutureTask.java" 122]}
   {:type java.lang.NullPointerException,
    :at
    [clojure.lang.Reflector
     invokeNoArgInstanceMember
     "Reflector.java"
     426]}],
  :trace
  [[clojure.lang.Reflector
    invokeNoArgInstanceMember
    "Reflector.java"
    426]
   [clindex.utils$normalize_path invokeStatic "utils.clj" 11]
   [clindex.utils$normalize_path invoke "utils.clj" 10]
   [clindex.scanner$scan_namespace_decl invokeStatic "scanner.clj" 309]
   [clindex.scanner$scan_namespace_decl invoke "scanner.clj" 301]
   [clindex.scanner$scan_namespaces$fn__2951 invoke "scanner.clj" 383]
   [clojure.core$pmap$fn__8462$fn__8463 invoke "core.clj" 7022]
   [clojure.core$binding_conveyor_fn$fn__5754 invoke "core.clj" 2030]
   [clojure.lang.AFn call "AFn.java" 18]
   [java.util.concurrent.FutureTask run "FutureTask.java" 264]
   [java.util.concurrent.ThreadPoolExecutor
    runWorker
    "ThreadPoolExecutor.java"
    1128]
   [java.util.concurrent.ThreadPoolExecutor$Worker
    run
    "ThreadPoolExecutor.java"
    628]
   [java.lang.Thread run "Thread.java" 834]]}}
```

**Comment by jpmonettas** [comment] 2019-12-07 18:35
> So it gets downloaded by tools-deps, but fails at the indexing phase?

I think this is the same error as before, it is showing after the indexing messages because of some laziness. 

> clindex is indeed dropping the configuration from the map before handing it to tools-deps, but after fixing that the failure is a bit different (and probably out of my depth)

Wow good catch! Completely missed that when added leiningen support. I just added a patch to clindex master to support repos from deps.edn and lein.

What I'm not being able to reproduce is the NPE, tests run fine for me after applying the patch.
I also added a little better exception handling in that part, maybe it helps debug the issue.

What can be happening for that NPE is that I'm using a custom version of tools.namespace, maybe something else is pulling a conflicting version. If it still happens we can try a `clj -Stree` and check that the only tools.namespace is `jpmonettas/tools.namespace 0.3.2`

**Comment by aisamu** [comment] 2019-12-07 20:21
* Confirmed that `jpmonettas/tools.namespace 0.3.2` is on the resolution tree

Ran it again against clindex master (with `pmap` replaced with `map`, since parallel execution doesn't mesh well with `prn` 😄), and got a very large stdout output:

```
Indexing  /project-folder/ for platform cljs
"[Info] Using maven repos " {"s3-maven" {:url "s3p://s3-maven-url/releases/", :no-auth true}, "central" {:url "https://repo1.maven.org/maven2/"}, "clojars" {:url "https://repo.clojars.org/"}}
...

"[Warning] couldn't scan namespace for ns-decl " (ns cljsjs.marked (:require ["marked" :as marked]))
"[Warning] couldn't scan namespace for ns-decl " (ns cljsjs.react (:require ["react" :as react] ["react-dom" :as react-dom] ["create-react-class" :as crc]))


..... (689 of those, including for namespaces like `cljs.core` and `cljsjs.*`

```

Stderr:
```shell
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Execution error (NullPointerException) at clindex.utils/reloadable-namespaces$fn (utils.clj:151).
null

Full report at:
/var/folders/s7/ngynyrg15v5f_588d_kqhy8w0000gn/T/clojure-12843971059787672976.edn
```
```clojure
{:clojure.main/message
 "Execution error (NullPointerException) at clindex.utils/reloadable-namespaces$fn (utils.clj:151).\nnull\n",
 :clojure.main/triage
 {:clojure.error/class java.lang.NullPointerException,
  :clojure.error/line 151,
  :clojure.error/symbol clindex.utils/reloadable-namespaces$fn,
  :clojure.error/source "utils.clj",
  :clojure.error/phase :execution},
 :clojure.main/trace
 {:via
  [{:type java.lang.NullPointerException,
    :at
    [clojure.string$starts_with_QMARK_
     invokeStatic
     "string.clj"
     364]}],
  :trace
  [[clojure.string$starts_with_QMARK_ invokeStatic "string.clj" 364]
   [clojure.string$starts_with_QMARK_ invoke "string.clj" 360]
   [clindex.utils$reloadable_namespaces$fn__6534
    invoke
    "utils.clj"
    151]
   [clojure.core$fn__8429$fn__8431 invoke "core.clj" 6840]
   [clojure.core.protocols$iter_reduce invokeStatic "protocols.clj" 49]
   [clojure.core.protocols$fn__8140 invokeStatic "protocols.clj" 75]
   [clojure.core.protocols$fn__8140 invoke "protocols.clj" 75]
   [clojure.core.protocols$fn__8088$G__8083__8101
    invoke
    "protocols.clj"
    13]
   [clojure.core$reduce invokeStatic "core.clj" 6828]
   [clojure.core$fn__8429 invokeStatic "core.clj" 6830]
   [clojure.core$fn__8429 invoke "core.clj" 6830]
   [clojure.core.protocols$fn__8167$G__8162__8176
    invoke
    "protocols.clj"
    175]
   [clojure.core$reduce_kv invokeStatic "core.clj" 6856]
   [clojure.core$reduce_kv invoke "core.clj" 6847]
   [clindex.utils$reloadable_namespaces invokeStatic "utils.clj" 150]
   [clindex.utils$reloadable_namespaces invoke "utils.clj" 146]
   [clindex.api$index_project_BANG_ invokeStatic "api.clj" 159]
   [clindex.api$index_project_BANG_ invoke "api.clj" 143]
   [clograms.core$re_index_all invokeStatic "core.clj" 30]
   [clograms.core$re_index_all invoke "core.clj" 27]
   [clograms.server$_main invokeStatic "server.clj" 38]
   [clograms.server$_main doInvoke "server.clj" 28]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.core$apply invokeStatic "core.clj" 665]
   [clojure.main$main_opt invokeStatic "main.clj" 514]
   [clojure.main$main_opt invoke "main.clj" 510]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]]}}
```

**Comment by jpmonettas** [comment] 2019-12-07 20:30
> Ran it again against clindex master (with pmap replaced with map, since parallel execution doesn't mesh well with prn), and got a very large stdout output

Yeah I need to move those prints to a logging library

Can you paste the output of `clj -Stree`?, maybe another tools.namespace is also there

**Comment by aisamu** [comment] 2019-12-07 20:48
> maybe another tools.namespace is also there

```
com.billpiel/sayid 0.0.18
  org.clojure/tools.namespace 0.3.1
```

🤦‍♂ very good catch! `clindex` tests still fail, though. Removing my system/user deps.edn completely didn't solve it.

But the error is a new one (progress!): 

```
$ clj -m clograms.server ~/project-folder/ cljs > out.txt
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Execution error (ExceptionInfo) at datascript.db/validate-val (db.cljc:821).
Cannot store nil as a value at [:db/add 458061236 :multi/dispatch-form nil]

Full report at:
/var/folders/s7/ngynyrg15v5f_588d_kqhy8w0000gn/T/clojure-4483028197369418451.edn
```
Here's [out.txt](https://github.com/jpmonettas/clograms/files/3935532/out.txt) from that command

And here's the full report: 
```clojure
{:clojure.main/message
 "Execution error (ExceptionInfo) at datascript.db/validate-val (db.cljc:821).\nCannot store nil as a value at [:db/add 458061236 :multi/dispatch-form nil]\n",
 :clojure.main/triage
 {:clojure.error/class clojure.lang.ExceptionInfo,
  :clojure.error/line 821,
  :clojure.error/cause
  "Cannot store nil as a value at [:db/add 458061236 :multi/dispatch-form nil]",
  :clojure.error/symbol datascript.db/validate-val,
  :clojure.error/source "db.cljc",
  :clojure.error/phase :execution},
 :clojure.main/trace
 {:via
  [{:type clojure.lang.ExceptionInfo,
    :message
    "Cannot store nil as a value at [:db/add 458061236 :multi/dispatch-form nil]",
    :data
    {:error :transact/syntax,
     :value nil,
     :context [:db/add 458061236 :multi/dispatch-form nil]},
    :at [datascript.db$validate_val invokeStatic "db.cljc" 821]}],
  :trace
  [[datascript.db$validate_val invokeStatic "db.cljc" 821]
   [datascript.db$validate_val invoke "db.cljc" 819]
   [datascript.db$transact_add invokeStatic "db.cljc" 999]
   [datascript.db$transact_add invoke "db.cljc" 997]
   [datascript.db$transact_tx_data invokeStatic "db.cljc" 1186]
   [datascript.db$transact_tx_data invoke "db.cljc" 1062]
   [datascript.core$with invokeStatic "core.cljc" 229]
   [datascript.core$with invoke "core.cljc" 222]
   [datascript.core$_transact_BANG_$fn__6126 invoke "core.cljc" 436]
   [clojure.lang.Atom swap "Atom.java" 37]
   [clojure.core$swap_BANG_ invokeStatic "core.clj" 2352]
   [clojure.core$swap_BANG_ invoke "core.clj" 2345]
   [datascript.core$_transact_BANG_ invokeStatic "core.cljc" 435]
   [datascript.core$_transact_BANG_ invoke "core.cljc" 432]
   [datascript.core$transact_BANG_ invokeStatic "core.cljc" 527]
   [datascript.core$transact_BANG_ invoke "core.cljc" 442]
   [datascript.core$transact_BANG_ invokeStatic "core.cljc" 524]
   [datascript.core$transact_BANG_ invoke "core.cljc" 442]
   [clindex.api$index_project_BANG_ invokeStatic "api.clj" 170]
   [clindex.api$index_project_BANG_ invoke "api.clj" 143]
   [clograms.core$re_index_all invokeStatic "core.clj" 30]
   [clograms.core$re_index_all invoke "core.clj" 27]
   [clograms.server$_main invokeStatic "server.clj" 38]
   [clograms.server$_main doInvoke "server.clj" 28]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.core$apply invokeStatic "core.clj" 665]
   [clojure.main$main_opt invokeStatic "main.clj" 514]
   [clojure.main$main_opt invoke "main.clj" 510]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]],
  :cause
  "Cannot store nil as a value at [:db/add 458061236 :multi/dispatch-form nil]",
  :data
  {:error :transact/syntax,
   :value nil,
   :context [:db/add 458061236 :multi/dispatch-form nil]}}}
```

**Comment by jpmonettas** [comment] 2019-12-07 21:15
Nice! that is a different error, looks like your sources contains a multimethod definition with a nil dispatch form, or some form that is not contemplated by clindex.

I just pushed a patch to treat those errors as warnings and prevent them crashing the app.

Take a look with current clindex master now.

Thanks for reporting all that stuff!

**Comment by aisamu** [comment] 2019-12-08 21:42
> Take a look with current clindex master now.

Works beautifully! 🎉 
The find-references feature is invaluable :) 

> I just pushed a patch to treat those errors as warnings and prevent them crashing the app.

That'd be the (single) instance of that, I suppose: 
```
"[Warning] no dispatch form for" (cljs.core/defmulti reducer) " inside " project-name.namespace.namespace
```



On a second note, here's what I also was writing here: 
> "It might be useful to add a note regarding the `tools.namespaces` shadowing. It can be easily avoided with the `-Srepro` flag, but without your tip the chances of me trying that would be pretty slim!"

I then went to the terminal to double-check that it'd indeed fail without the flag, and you can already imagine what happened :) 
```
org.clojure/tools.namespace detected on classpath. Clindex uses
a modified version of tools.namespace so exclude it from the classpath 
before continuing
```

Again, superb!
Thanks for being so responsive (and on a weekend to boot)!

**Comment by jpmonettas** [comment] 2019-12-09 00:00
Happy to hear it works and that you find it useful!
Thanks for your time also and your help with debugging. If you have any suggestions or features you would like to see feel free to create more issues, it is a exploratory tool so I'm open to suggestions.
I will close this issue now, please reopen if needed.

**Closed by jpmonettas** 2019-12-09 00:00 UTC
